#!/usr/bin/env python

from odin.architectures import log_reg
from odin.io import io

x,y = io.read_x_y('/Users/hclimente/projects/odin/data/genesis.npy', categorical = True)
snps = io.read_map('/Users/hclimente/projects/genewa/data/genesis/genesis.processed.map')

model = log_reg.LogReg()
model.run(x, y, snps['chr'])
